In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataListrik.csv')
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
X = np.array(dataset.iloc[:, :-1]) 
y = np.array(dataset.iloc[:,-1]) 

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
#masih kolom
print(y)
y.shape

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


(9568,)

In [7]:
#menjadi perbaris
y = y.reshape(len(y), 1)
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Featur Scaling 

In [9]:
#SVR sensitif perbedaan nilai pada matrix / vektor
#Featur Scaling --> agar perbandingan nilainya tidak terlalu jauh

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [10]:
#Output dari X DAN y hampir sama
print(X)

[[-0.62951938 -0.98729659  1.8204884  -0.00951935]
 [ 0.74190911  0.68104512  1.1418628  -0.97462052]
 [-1.95129733 -1.17301765 -0.18507756  1.2898397 ]
 ...
 [ 1.56583973  1.57581141 -0.05709854 -2.52261812]
 [ 0.64797565  1.19177803  0.1011913  -0.74790051]
 [ 0.26150656  0.64641916  0.66867722 -0.37254534]]


In [11]:
print(y)

[[ 0.52120807]
 [-0.58566442]
 [ 2.00367889]
 ...
 [-1.45288056]
 [-1.09134518]
 [-0.06357687]]


## Training SVR model on the whole dataset 

In [12]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
#X, y disini adalah yang sudah mengalami transformasi scaling
regressor.fit(X,y)

C:\Users\Bayu Nusman\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

## Predicting a new result

In [14]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])).reshape(-1, 1))
#reshape (2 dimensi)
#inverse --> membalikan
#matrix 2 dimensi isinya cuma 1

ValueError: X has 1 features, but StandardScaler is expecting 3 features as input.

In [ ]:
# grafik scatter
# data yang dimasukkan sudah di scaling
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color='red')

# grafik linear regresi
# degree nya diubah menjadi 4
plt.plot(sc_X.inverse_transform(X), sc_y.inverse_transform(regressor.predict(X).reshape(-1, 1)), color='blue')
plt.title('Truth or bluff (SVR)')
plt.xlabel('Level position')
plt.ylabel('Salary')
plt.show()


## Visualising SVR Result (high resolution)

In [13]:
#regressor hanya memahami yang sudah di fitur scaling
#posisi bentuk yang asli
#model regresi hanya bisa dibuat dengan fitur scaling
X_grid = np.arange(min(sc_X.inverse_transform(X)), max(sc_X.inverse_transform(X)), 0.1)
X_grid = X_grid.reshape(len(X_grid),1 )
#plt.scatter(X, y, color = 'red')
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_X.transform(X_grid)).reshape(-1, 1)), color = 'blue')
plt.title('Truth of bluff (SVR) - Higher resolution')
plt.xlabel('Level position')
plt.ylabel('Salary')
plt.show()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()